
[jetpack]
	#How fast can you move forwards? 0.0 = vanilla speed
	#Range: 0.0 ~ 15.0
	forward_speed_boost = 2.0
	#How fast can you move sideways / backwards? 0.0 = vanilla speed
	#Range: 0.0 ~ 15.0
	strafe_speed_boost = 0.0
	#How fast can you move upwards? 0.15 = default mekanism
	#Range: 0.0 ~ 5.0
	vertical_speed = 0.15
	#What is the top speed when moving upwards in NORMAL mode? 0.5 = default mekanism
	#Range: 0.0 ~ 100.0
	max_vertical_speed_normal = 0.5
	#What is the top speed when moving up & down in HOVER mode? 0.2 = default mekanism
	#Range: 0.0 ~ 100.0
	max_vertical_speed_hover = 0.2

